name=input('What is your name ? ')
print('UGH, I HATE YOU ' + name.upper())
favorite_color=input('What is your favorite color? ')
print('UGH, I HATE '+ favorite_color.upper())
subject=input('What is your favorite subject in school? ')
print('UGH, I HATE' + subject.upper())
print(I HATE EVERYTHING!)
day=input('What is your favorite day? ')
print('I HATE' + day.upper())